version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  build-upload-image:
    docker:
      - image: circleci/node:14 # Use a CircleCI Docker image as the build environment
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Use the appropriate Docker version

      # Build the Docker image
      - run:
          name: Build Docker Image
          command: docker build -t harishbabua/udablueimage:latest .

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push harishbabua/udablueimage:latest

workflows:
  deployment:
    jobs:
      - build-upload-image
